plantilla base agregada en views
BiancaRomeroG/Proyecto_SI1 pull request #27
Opened 2021-11-22 20:22 UTC by BiancaRomeroG

plantila master.blade.php creada en folder views

resolve #21

2021-11-22 20:30 UTC, JrogeT requested changes

2021-11-22 20:30 UTC, JrogeT commented on resources/views/home.blade.php
>  <body>
mover etiquetas body a master

2021-11-22 20:30 UTC, JrogeT commented on resources/views/home.blade.php
>  </body>
mover etiquetas body a master

2021-11-22 20:30 UTC, JrogeT commented on resources/views/login.blade.php
>  <body class="bg-light">
mover a máster

2021-11-22 20:30 UTC, JrogeT commented on resources/views/login.blade.php
> +</body>
mover a máster

2021-11-22 20:30 UTC, JrogeT commented on resources/views/master.blade.php
> +<body>
body repetido

2021-11-22 20:50 UTC, BiancaRomeroG commented on resources/views/login.blade.php
> +</body>
no entiendo xd donde vez body repetido en el master

2021-11-22 20:51 UTC, BiancaRomeroG commented on resources/views/login.blade.php
> +</body>
![Uploading WhatsApp Image 2021-11-22 at 4.51.32 PM.jpeg…]()

2021-11-22 21:00 UTC, JrogeT requested changes

2021-11-22 21:00 UTC, JrogeT commented on resources/views/master.blade.php
> +    @yield('content')
cambiar por section

2021-11-22 21:13 UTC, BiancaRomeroG commented on resources/views/master.blade.php
> +    @yield('content')
ya lo cambie

2021-11-23 03:04 UTC, JrogeT approved these changes

2021-11-23 03:05 UTC, merged