Features/pagina registro materia
BiancaRomeroG/Proyecto_SI1 pull request #39
Opened 2021-11-25 00:06 UTC by JhoelFloresS

resolve #34 

   ISSUE_NUMBER: 34

2021-11-25 11:37 UTC, JrogeT requested changes

2021-11-25 11:37 UTC, JrogeT commented on app/Http/Controllers/materiaController.php
> +        return view("/materiaRegistro");
quitar `/`

solo debe quedar:
`return view("materiaRegistro");`

2021-11-26 15:54 UTC, JhoelFloresS commented on app/Http/Controllers/materiaController.php
> +        return view("/materiaRegistro");
slash quitado

2021-11-26 22:17 UTC, JrogeT approved these changes

2021-11-26 22:18 UTC, merged